In [1]:
from parsers import *

/home/nlonyuk/Desktop/nazar/thesis/tusp-pddl-post-processing/plan_parsers/parsing.py:48: SyntaxWarning: invalid escape sequence '\d'
  NUMBER_REGEX = "[-+]?[.]?[\d]+(?:,\d\d\d)*[\.]?\d*(?:[eE][-+]?\d+)?"

In [2]:
planner_output = parse_enhsp_file('../data/unparsed_plans/enhsp_detailed_unparsed.txt')
planner_output.show_stats()

    cost  expansions  plan length  searchtime
0  227.0      1848.0         71.0     26124.0
1  228.0      3073.0         71.0     36277.0
2  229.0      1623.0         71.0     23101.0
3  230.0      4570.0         71.0     49036.0
4  237.0       214.0         71.0      8329.0
5  238.0       196.0         75.0      8345.0
6  240.0       253.0         74.0      9442.0
7   -1.0        -1.0         75.0        -1.0

In [3]:
planner_output = parse_metricff_file('../data/unparsed_plans/metricff_detailed_unparsed.txt')
planner_output.show_stats()

   cost  expansions  plan length  searchtime
0  85.0        -1.0         28.0      4445.3

In [4]:
planner_output = parse_nfd_file('../data/unparsed_plans/nfd_detailed_unparsed.txt')
planner_output.show_stats()

   cost  expansions  plan length  searchtime
0  66.0        -1.0         23.0        -1.0

In [5]:
planner_output = parse_optic_file('../data/unparsed_plans/optic_simple_unparsed.txt')
planner_output.show_stats()

     cost  expansions  plan length  searchtime
0  87.111        -1.0         19.0        7.77

In [6]:
planner_output = parse_tfd_file('../data/unparsed_plans/tfd_detailed_unparsed.txt')
planner_output.show_stats()

    cost  expansions  plan length  searchtime
0  331.0       283.0         45.0        70.0
1  335.0         1.0         46.0        10.0